set(_CATKIN_CURRENT_PACKAGE "evanhateros")
set(evanhateros_VERSION "0.0.0")
set(evanhateros_MAINTAINER "jetson <jetson@todo.todo>")
set(evanhateros_PACKAGE_FORMAT "2")
set(evanhateros_BUILD_DEPENDS "rospy" "std_msgs" "message_generation")
set(evanhateros_BUILD_EXPORT_DEPENDS "rospy" "std_msgs")
set(evanhateros_BUILDTOOL_DEPENDS "catkin")
set(evanhateros_BUILDTOOL_EXPORT_DEPENDS )
set(evanhateros_EXEC_DEPENDS "rospy" "std_msgs" "message_runtime")
set(evanhateros_RUN_DEPENDS "rospy" "std_msgs" "message_runtime")
set(evanhateros_TEST_DEPENDS )
set(evanhateros_DOC_DEPENDS )
set(evanhateros_URL_WEBSITE "")
set(evanhateros_URL_BUGTRACKER "")
set(evanhateros_URL_REPOSITORY "")
set(evanhateros_DEPRECATED "")