# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from evanhateros/car_control.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class car_control(genpy.Message):
  _md5sum = "5d2cc03a4196a5dac5509c8ff21f0969"
  _type = "evanhateros/car_control"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
bool shutdown
float32 velocity
float32 rotation
"""
  __slots__ = ['id','shutdown','velocity','rotation']
  _slot_types = ['int32','bool','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,shutdown,velocity,rotation

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(car_control, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.shutdown is None:
        self.shutdown = False
      if self.velocity is None:
        self.velocity = 0.
      if self.rotation is None:
        self.rotation = 0.
    else:
      self.id = 0
      self.shutdown = False
      self.velocity = 0.
      self.rotation = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_iB2f().pack(_x.id, _x.shutdown, _x.velocity, _x.rotation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.id, _x.shutdown, _x.velocity, _x.rotation,) = _get_struct_iB2f().unpack(str[start:end])
      self.shutdown = bool(self.shutdown)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_iB2f().pack(_x.id, _x.shutdown, _x.velocity, _x.rotation))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.id, _x.shutdown, _x.velocity, _x.rotation,) = _get_struct_iB2f().unpack(str[start:end])
      self.shutdown = bool(self.shutdown)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_iB2f = None
def _get_struct_iB2f():
    global _struct_iB2f
    if _struct_iB2f is None:
        _struct_iB2f = struct.Struct("<iB2f")
    return _struct_iB2f
